// Bundles every extension entry point and escapes non-ASCII in the output.
//
// Two kinds of build happen here.
//
// 1. The DESIGNER CONTENT SCRIPTS (AD, PD) are built together as ONE code-split
//    ES-module graph into dist/modules/. This exists so the textarea editor's
//    CodeMirror (~600 KB) can be loaded on first use instead of on every page
//    load — src/designer/features/textarea-editor/index.ts reaches it via
//    `import()`.
//
//    They MUST be one `bun build --splitting` call, not one call per entry.
//    The lazy editor imports designer/core/settings, designer/ui/modal-lock,
//    designer/ui/toast and the settings modal, which are module-level
//    singletons. Built separately, the editor chunk would carry its own
//    copies: the `settings` store would have two subscriber lists and the
//    modal lock two counters — so the keyboard shortcuts would stop seeing
//    that the editor is open. One graph puts shared modules in shared chunks,
//    and a page loads each chunk once.
//
//    Content scripts cannot be ES modules themselves, so dist/ad-content.js
//    and dist/pd-content.js are small generated loaders that `import()` the
//    real entry. The loaders keep the paths src/background/content-scripts.ts
//    registers, so no registration changes. Both browsers require the
//    imported files to be web_accessible_resources (verified: without it
//    Chromium and Firefox both refuse the import) — see manifest.json.
//
// 2. EVERYTHING ELSE is built standalone, one invocation per entry, so the
//    output lands flat in dist/ (a single shared build would mirror the src/
//    subdirectories). None of these are pages that load CodeMirror.
//
// HTML pages are not handled here: scripts/pack.mjs copies them from src/ to
// the root of each packaged tree, where their <script src="dist/…"> resolves.
import { execSync } from 'node:child_process';
import { readdirSync, rmSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const run = (cmd) => execSync(cmd, { cwd: root, stdio: 'inherit' });
const escape = (file) => run(`node scripts/escape-non-ascii.mjs ${file}`);

// Chunk names carry a content hash, so a stale chunk from an earlier build
// would otherwise survive into dist/ and ship.
rmSync(path.join(root, 'dist'), { recursive: true, force: true });

// ---- 1. designer content scripts: one split graph + loaders ---------------
const MODULES_DIR = 'dist/modules';
const splitEntries = ['ad-content', 'pd-content'];

run(
  `bun build ${splitEntries.map((n) => `src/designer/${n}.ts`).join(' ')} ` +
    `--splitting --minify --outdir ${MODULES_DIR} ` +
    `--entry-naming '[name].[ext]' --chunk-naming 'chunk-[hash].[ext]'`
);
for (const file of readdirSync(path.join(root, MODULES_DIR))) {
  escape(`${MODULES_DIR}/${file}`);
}

for (const name of splitEntries) {
  writeFileSync(
    path.join(root, 'dist', `${name}.js`),
    `// Generated by scripts/build.mjs. Content scripts cannot be ES modules, so\n` +
      `// this loads the real one. See the header of build.mjs.\n` +
      `import(chrome.runtime.getURL('${MODULES_DIR}/${name}.js')).catch((e) =>\n` +
      `  console.error('[belz] content script failed to load:', e));\n`
  );
}

// ---- 2. everything else: standalone bundles --------------------------------
const standalone = [
  { src: 'src/pd-inspector-page/index.ts', out: 'pd-inspector.js' },
  { src: 'src/background/index.ts', out: 'background.js' },
  { src: 'src/options/index.ts', out: 'options.js' },
  { src: 'src/devtools/devtools-page.ts', out: 'devtools-page.js' },
  { src: 'src/devtools/ad-network/panel.ts', out: 'panel.js' },
  { src: 'src/devtools/pd-inspector/panel.ts', out: 'panel-pd.js' }
];

for (const { src, out } of standalone) {
  run(`bun build ${src} --minify --outfile dist/${out}`);
  escape(`dist/${out}`);
}

// ---- 3. guard: every stateful module bundled exactly once ------------------
// Throws (failing the build) if the rule in the header was broken.
run('node scripts/check-singletons.mjs');

console.log('extension build complete');
